apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-mvn-settings
  namespace: autojenkins
data:
  settings.xml: |
    <settings>
        <servers>
            <server>
                <id>nexus-releases</id>
                <username>admin</username>
                <password>1234</password>
            </server>
        </servers>
    </settings>
