apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: {{ .Values.sonar.namespace }}
  labels:
    app: sonar
spec:
  selector:
    app: sonar
  ports:
    - name: http
      port: 9000
      targertPort: 9000
  type: ClusterIP
