apiVersion: v1
kind: Pod
metadata:
  name: generic-agent
  namespace: autojenkins
spec:
  initContainers:
    - name: init-apk-db
      image: srmmll/generic-agent:0.0.0
      command: ["sh", "-c"]
      env:
        - name: CLEAR_CACHE_PATHS
          value: "true"
      args: ["/init-container-script.sh"]
      volumeMounts:
        - name: agent-cache
          mountPath: /opt
  containers:
    - name: generic-agent
      image: srmmll/generic-agent:0.0.0
      imagePullPolicy: Always
      command: ["bash", "-c"]
      args: ["sleep 7000"]
      volumeMounts:
        - name: agent-cache
          mountPath: /opt
  volumes:
    - name: agent-cache
      persistentVolumeClaim:
        claimName: autojenkins-agent-cache
